layout: page
title: My website
subtitle: Is this really where I will tell my friends way too much about me?
use-site-title: true
exclude:
  - Makefile
  - README.md
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - vendor
  - package.json
  - .babelrc
  - yarn.lock
  - package-lock.json
  - webpack.config.js
  - node_modules
  - Dockerfile
  - docker_compose.yml

# Markdown
